name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Cache Bazel dependencies'
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/bazel/*/*/external
          key: bazel-${{ hashFiles('MODULE.bazel') }}
          restore-keys: |
            bazel-
      - name: 'Test'
        shell: bash
        run: bazelisk test --lockfile_mode=error --test_output=errors //...
